// <auto-generated />
using System;
using AspNetCoreTodo.Services.Implementations;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AspNetCoreTodo.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.1");

            modelBuilder.Entity("AspNetCoreTodo.Models.CommentModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreationTime")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TodoId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TodoId");

                    b.ToTable("Comments", (string)null);
                });

            modelBuilder.Entity("AspNetCoreTodo.Models.TodoModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreationTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("_body")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Body");

                    b.Property<string>("_title")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Title");

                    b.Property<DateTimeOffset>("_updateTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("UpdateTime");

                    b.HasKey("Id");

                    b.HasIndex("CreationTime");

                    b.HasIndex("_title");

                    b.HasIndex("_updateTime");

                    b.ToTable("Todos", (string)null);
                });

            modelBuilder.Entity("AspNetCoreTodo.Models.CommentModel", b =>
                {
                    b.HasOne("AspNetCoreTodo.Models.TodoModel", null)
                        .WithMany("_comments")
                        .HasForeignKey("TodoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AspNetCoreTodo.Models.TodoModel", b =>
                {
                    b.Navigation("_comments");
                });
#pragma warning restore 612, 618
        }
    }
}
